name: YouTube Scraper Job

on:
  schedule:
    - cron: '0 */5 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade requests yt-dlp

      - name: Create cookies file
        run: |
          cat << 'EOF' > cookies.txt
          ${{ secrets.YOUTUBE_COOKIES }}
          EOF

      - name: Run YouTube Scraper
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_NAMESPACE_ID: ${{ secrets.CF_NAMESPACE_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: python main.py
